### ISSUE TITLE
Error reading field 'version': java.nio.BufferUnderflowException

### ISSUE THREAD

**Issue by ipcpu** [zalando-incubator/remora#41] opened 2018-04-10 07:00 UTC
I get an error when used about 7days.

the API interface tell about "Internal Error! Please check logs"

2018-04-10 06:57:59,785 - [DEBUG] - [remora-akka.actor.default-dispatcher-95] akka.io.TcpListener - New connection accepted
2018-04-10 06:57:59,801 - [INFO] - [remora-akka.actor.default-dispatcher-95] KafkaClientActor - Received request for consumer list
2018-04-10 06:58:06,134 - [DEBUG] - [remora-akka.actor.default-dispatcher-105] akka.io.TcpListener - New connection accepted
2018-04-10 06:58:06,142 - [INFO] - [remora-akka.actor.default-dispatcher-105] KafkaClientActor - Received request for group_new_device_teu
2018-04-10 06:58:06,176 - [ERROR] - [remora-akka.actor.default-dispatcher-107] akka.actor.ActorSystemImpl - Request received an exception: Error reading field 'version': java.nio.BufferUnderflowException
org.apache.kafka.common.protocol.types.SchemaException: Error reading field 'version': java.nio.BufferUnderflowException
	at org.apache.kafka.common.protocol.types.Schema.read(Schema.java:76)
	at org.apache.kafka.clients.consumer.internals.ConsumerProtocol.deserializeAssignment(ConsumerProtocol.java:105)
	at kafka.admin.AdminClient$$anonfun$12.apply(AdminClient.scala:326)
	at kafka.admin.AdminClient$$anonfun$12.apply(AdminClient.scala:323)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at kafka.admin.AdminClient.describeConsumerGroup(AdminClient.scala:323)
	at kafka.admin.ConsumerGroupCommand$KafkaConsumerGroupService.collectGroupAssignment(ConsumerGroupCommand.scala:428)
	at kafka.admin.ConsumerGroupCommand$ConsumerGroupService$class.describeGroup(ConsumerGroupCommand.scala:173)
	at kafka.admin.ConsumerGroupCommand$KafkaConsumerGroupService.describeGroup(ConsumerGroupCommand.scala:416)
	at RemoraKafkaConsumerGroupService$$anonfun$describeConsumerGroup$1$$anonfun$apply$2.apply(RemoraKafkaConsumerGroupService.scala:54)
	at RemoraKafkaConsumerGroupService$$anonfun$describeConsumerGroup$1$$anonfun$apply$2.apply(RemoraKafkaConsumerGroupService.scala:51)
	at nl.grons.metrics.scala.Timer.time(Timer.scala:54)
	at RemoraKafkaConsumerGroupService$$anonfun$describeConsumerGroup$1.apply(RemoraKafkaConsumerGroupService.scala:51)
	at RemoraKafkaConsumerGroupService$$anonfun$describeConsumerGroup$1.apply(RemoraKafkaConsumerGroupService.scala:51)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by marky-mark** [comment] 2018-04-18 07:16
Did the issue persist and remora had to be restarted to solve the issue? Or did it continue as normal after?

**Comment by oded-dd** [comment] 2018-08-09 16:38
We have the same isse
+1

**Comment by GnanasoundariSoundarajan** [comment] 2018-08-10 05:45
We are also facing the same issue
+1

**Comment by marky-mark** [comment] 2018-09-22 09:18
can you all let me know specifically which Kafka versions you are using?

**Comment by GnanasoundariSoundarajan** [comment] 2018-09-23 10:12
Kafka version 1.1.0

**Comment by marky-mark** [comment] 2018-09-23 11:17
The error stack shows that the error is in the Kafka Admin Client.

KSQL seems to have the same issue https://github.com/confluentinc/ksql/issues/1014
And Kafka resolved this in 10.2.0 https://issues.apache.org/jira/browse/KAFKA-4349

I'll dig more into the code and see if there is something i can do

**Comment by marky-mark** [comment] 2018-09-23 15:56
i've created a PR https://github.com/zalando-incubator/remora/pull/54 to upgrade to 1.1.1. 

The Kafka Client is sending back the error and looks to be working as designed since the exception handler is only feeding back what is received. The application should still run and will return offsets once kafka exits the state it is in.

If you wanted you could open up a bug with Kafka via the link in the previous post.

**Comment by marky-mark** [comment] 2018-10-08 13:33
This is the release https://github.com/zalando-incubator/remora/tree/v1.0.6 for using kafka 1.1.1. Closing this issue for now

**Closed by marky-mark** 2018-10-08 13:33 UTC
